name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        sudo apt install libboost-all-dev

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build
        ls -Gghl build/server build/client
